- hosts: docker_servers
  gather_facts: yes
  become: yes
  tasks:
    
    - name: Install Packages Neccesary to Add Docker-CE Keys
      #become: yes
      apt:
        name: "{{ packages }}"
        state: latest
        update_cache: yes
        cache_valid_time: 3600 #Only run "update_cache=yes" if the last one is more than N seconds ago
      vars:
        packages:
        - curl
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common

    - name: Download and Add Docker-CE Key
      #become: yes
      apt_key:
          url: https://download.docker.com/linux/ubuntu/gpg
          state: present
          id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    
    - name: Add Docker Repo
      #become: yes
      apt_repository:
          repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable"
          state: present
          update_cache: yes
          mode: 0644
          validate_certs: yes
          
    - name: Install Docker-CE
      #become: yes
      apt:
        name: "{{ packages }}"
        state: latest
        update_cache: yes
        cache_valid_time: 3600
      vars:
        packages:
        - docker-ce
